# Generated by Django 4.1.3 on 2023-06-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newPage', '0002_alter_tipousuario_idtipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
